version: "1.0"
name: "Grok-Event-Handler"

# 1. TRIGGER: Webhook for Event Processing
trigger:
  type: webhook
  # Dedicated endpoint for this specific event type
  route: "/api/v1/events/social-alert"
  # Secure the endpoint with token auth
  auth_token: ${WEBHOOK_AUTH_TOKEN}
  # HTTP method
  method: POST
  # Expected payload structure documentation
  schema:
    event_type: "string"
    timestamp: "iso8601"
    content: "string"
    metadata: "object"

# 2. RESOURCES: Grok Agent with Constrained Prompt
resources:
  - id: social_analyst
    provider: grok
    model: grok-beta
    # Pre-defined behavioral constraints for this event handler
    system_prompt: |
      You are a Social Media Intelligence Analyst specializing in real-time event monitoring.
      
      CONSTRAINTS:
      - Focus ONLY on factual observations from social media data
      - Identify sentiment: POSITIVE, NEGATIVE, NEUTRAL, or MIXED
      - Flag potential misinformation or manipulation campaigns
      - Extract key topics and trending hashtags
      - Identify influential accounts driving the conversation
      
      OUTPUT FORMAT (JSON):
      {
        "sentiment": "POSITIVE|NEGATIVE|NEUTRAL|MIXED",
        "confidence": 0.0-1.0,
        "key_topics": ["topic1", "topic2"],
        "trending_hashtags": ["#tag1", "#tag2"],
        "influential_accounts": ["@user1", "@user2"],
        "misinformation_risk": "LOW|MEDIUM|HIGH",
        "summary": "Brief 2-3 sentence summary",
        "recommended_action": "MONITOR|ENGAGE|ESCALATE|IGNORE"
      }
      
      Be concise, objective, and actionable. No speculation.

# 3. WORKFLOW: Process Event and Return Structured Response
workflow:
  type: sequential
  steps:
    - id: analyze_event
      agent: social_analyst
      instruction: |
        EVENT RECEIVED:
        Type: {trigger.payload.event_type}
        Timestamp: {trigger.payload.timestamp}
        
        CONTENT TO ANALYZE:
        {trigger.payload.content}
        
        ADDITIONAL METADATA:
        {trigger.payload.metadata}
        
        Analyze this social media event using X (Twitter) real-time data and intelligence.
        Apply the constraints defined in your system prompt.
        Return your analysis in the specified JSON format.
    
    # Step 2: Format and validate the response
    - id: format_response
      type: action
      action: json.validate_and_format
      params:
        input: ${analyze_event.output}
        # Ensure the response matches our expected schema
        strict: true
        # Add response metadata
        envelope:
          event_id: ${trigger.payload.event_id}
          processed_at: ${workflow.timestamp}
          handler: "grok-social-analyst"
          status: "completed"
